In [2]:
import pandas as pd
import numpy as np

In [3]:
df_steam = pd.read_csv("steam-playtime-2021-06-07.csv", index_col="game_title")
df_steam

                                           playtime_forever
game_title
GARRY'S MOD                                            3287
MIRROR'S EDGE                                           523
BROTHERS IN ARMS  ROAD TO HILL 30                         0
BROTHERS IN ARMS  HELL'S HIGHWAY                          0
BROTHERS IN ARMS  EARNED IN BLOOD                        38
...                                                     ...
DIRT RALLY                                                0
DESTINY 2                                                 0
MIRROR'S EDGE CATALYST                                  103
INJUSTICE  GODS AMONG US ULTIMATE EDITION                 0
LITTLE NIGHTMARES                                         0

[129 rows x 1 columns]

In [4]:
df_hltb = pd.read_csv("hltb-playtime-2021-06-07.csv", index_col="game_title")
df_hltb

                          time_to_beat
game_title
ADVENTURE CAPITALIST              9955
AMNESIA  THE DARK DESCENT          497
BATTLERITE                           -
BAYONETTA                          771
BIOSHOCK                           846
...                                ...
UNTURNED                          3010
VRCHAT                           12086
WAR THUNDER                       1545
WARFRAME                         34862
ZEZENIA ONLINE                       -

[123 rows x 1 columns]

In [5]:
df_games = pd.concat([df_steam, df_hltb], axis=1).dropna()
df_games

                                   playtime_forever time_to_beat
game_title
GARRY'S MOD                                  3287.0         9956
MIRROR'S EDGE                                 523.0          402
BROTHERS IN ARMS  ROAD TO HILL 30               0.0          493
BROTHERS IN ARMS  HELL'S HIGHWAY                0.0          491
BROTHERS IN ARMS  EARNED IN BLOOD              38.0          460
...                                             ...          ...
METRO EXODUS                                    0.0         1254
ECHO OF SOUL                                    1.0            -
DIRT RALLY                                      0.0         3281
DESTINY 2                                       0.0         1478
LITTLE NIGHTMARES                               0.0          231

[100 rows x 2 columns]

In [6]:
df_games["time_to_beat"].replace("-", np.nan, inplace=True)

In [7]:
df_games.dropna(inplace=True)

In [8]:
df_games["time_to_beat"] = df_games["time_to_beat"].astype("float64")

In [9]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, GARRY'S MOD to LITTLE NIGHTMARES
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   playtime_forever  82 non-null     float64
 1   time_to_beat      82 non-null     float64
dtypes: float64(2)
memory usage: 1.9+ KB

In [10]:
df_games = df_games.assign(played_ratio=(df_games["playtime_forever"]/df_games["time_to_beat"]) * 100)

In [11]:
df_games.sort_values("played_ratio", ascending=False).head(40)

,playtime_forever,time_to_beat,played_ratio
game_title,,,
BIOSHOCK,2564.0,846.0,303.073286
PORTAL 2,1143.0,617.0,185.251216
MOONBASE ALPHA,114.0,80.0,142.500000
RISE OF THE TOMB RAIDER,1610.0,1206.0,133.499171
MIRROR'S EDGE,523.0,402.0,130.099502
HELLBLADE SENUA'S SACRIFICE,603.0,484.0,124.586777
TOMB RAIDER,965.0,864.0,111.689815
RACE 07,397.0,369.0,107.588076
METAL GEAR SOLID V GROUND ZEROES,206.0,201.0,102.487562
THE WITCHER 3 WILD HUNT,5731.0,6049.0,94.742933
AMNESIA THE DARK DESCENT,450.0,497.0,90.543260
BIOSHOCK INFINITE,736.0,823.0,89.428919
LEFT 4 DEAD 2,441.0,931.0,47.368421
DOOM,410.0,868.0,47.235023
PAYDAY THE HEIST,423.0,948.0,44.620253
BAYONETTA,335.0,771.0,43.450065
CASTLE CRASHERS,255.0,615.0,41.463415
GARRY'S MOD,3287.0,9956.0,33.015267
SPACE FARMERS,86.0,261.0,32.950192
BIOSHOCK 2,241.0,770.0,31.298701
PATH OF EXILE,1299.0,4367.0,29.745821
UNTURNED,839.0,3010.0,27.873754
NO MORE ROOM IN HELL,117.0,454.0,25.770925
HITMAN 2 SILENT ASSASSIN,230.0,903.0,25.470653
SHADOW OF THE TOMB RAIDER,288.0,1260.0,22.857143
THE WITCHER,544.0,2778.0,19.582433
PAYDAY 2,1175.0,7063.0,16.635990
METAL GEAR SOLID V THE PHANTOM PAIN,721.0,4742.0,15.204555
COUNTER-STRIKE GLOBAL OFFENSIVE,2491.0,17477.0,14.253018
CRY OF FEAR,78.0,601.0,12.978369
HITMAN ABSOLUTION,118.0,939.0,12.566560
METRO 2033,70.0,629.0,11.128776
THE TURING TEST,36.0,355.0,10.140845
THE CAT LADY,53.0,538.0,9.851301
CALL OF DUTY BLACK OPS II,40.0,478.0,8.368201
BROTHERS IN ARMS EARNED IN BLOOD,38.0,460.0,8.260870
HAWKEN,18.0,292.0,6.164384
RYSE SON OF ROME,17.0,437.0,3.890160
NEVERWINTER,192.0,5059.0,3.795216
COLD WAR,15.0,417.0,3.597122

In [17]:
print(f'Average played = {round(df_games["played_ratio"].mean(), 2)}%')

Average played = 27.38%